/**
 * Content database schema (PostgreSQL 17, Drizzle ORM). Phase B.
 * Design and rules: docs/admin-database.md; approved architecture §17, review §C.
 *
 * Pattern for every translatable entity:
 *   <entity>              language-independent data: stable key, status, order, relations, media
 *   <entity>_translations one row per language: texts, slug, SEO texts, translation status
 *
 * - Primary keys are UUIDv7 generated by the application; `key` is the stable text ID of the
 *   content layer (e.g. "project-solbar-israel"), unique and never changed.
 * - Relations between content entities are foreign keys with ON DELETE RESTRICT, so a
 *   referenced item can never disappear silently. Translation and child rows cascade.
 * - JSONB only for ordered lists inside a translation and code-defined slot maps; every JSONB
 *   column has a Zod schema in @soltex/core/content (jsonb.ts) and the table has schema_version.
 * - `page_list_items.structure` is `json`, not `jsonb`: it is an arbitrary code-defined object
 *   whose key order is part of the content (jsonb would reorder keys). See docs/admin-database.md.
 */
import { sql } from 'drizzle-orm';
import {
  type AnyPgColumn,
  bigint,
  boolean,
  check,
  customType,
  index,
  date,
  integer,
  json,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';
import { v7 as uuidv7 } from 'uuid';

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const contentStatus = pgEnum('content_status', ['draft', 'published', 'archived']);
export const translationState = pgEnum('translation_state', ['missing', 'in_progress', 'approved']);
export const mediaKind = pgEnum('media_kind', ['image', 'video']);
export const pageKind = pgEnum('page_kind', ['page', 'template']);
export const patentLegalStatus = pgEnum('patent_legal_status', ['granted', 'application']);
export const redirectSource = pgEnum('redirect_source', ['manual', 'slug_change', 'import']);

// ---------------------------------------------------------------------------
// Shared column sets
// ---------------------------------------------------------------------------

const pk = () => uuid('id').primaryKey().$defaultFn(() => uuidv7());
const stableKey = () => text('key').notNull().unique();
const audit = () => ({
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  // Users are never deleted (only disabled), so these references are RESTRICT (Phase C).
  createdBy: uuid('created_by').references((): AnyPgColumn => users.id, { onDelete: 'restrict' }),
  updatedBy: uuid('updated_by').references((): AnyPgColumn => users.id, { onDelete: 'restrict' }),
});

/** Columns of every publishable content entity. */
const entity = () => ({
  id: pk(),
  key: stableKey(),
  status: contentStatus('status').notNull().default('draft'),
  position: integer('position').notNull(),
  sourceLocale: text('source_locale')
    .notNull()
    .default('en')
    .references(() => locales.code),
  version: integer('version').notNull().default(1),
  publishedAt: timestamp('published_at', { withTimezone: true }),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  schemaVersion: smallint('schema_version').notNull().default(1),
  ...audit(),
});

/** Columns of every translation row (one row per entity and language). */
const translation = () => ({
  locale: text('locale')
    .notNull()
    .references(() => locales.code),
  /** null for the source language; workflow state for translations. */
  trStatus: translationState('tr_status'),
  /** Hash of the source-language fields when this translation was approved. */
  approvedSourceHash: text('approved_source_hash'),
  approvedAt: date('approved_at', { mode: 'string' }),
  schemaVersion: smallint('schema_version').notNull().default(1),
  ...audit(),
});

/** Per-language SEO texts of routable entities (null = frontend default template). */
const seoTexts = () => ({
  seoMetaTitle: text('seo_meta_title'),
  seoMetaDescription: text('seo_meta_description'),
});

// ---------------------------------------------------------------------------
// Reference data
// ---------------------------------------------------------------------------

export const locales = pgTable('locales', {
  code: text('code').primaryKey(),
  position: smallint('position').notNull().unique(),
  isSource: boolean('is_source').notNull().default(false),
});

// ---------------------------------------------------------------------------
// Media
// ---------------------------------------------------------------------------

export const media = pgTable('media', {
  id: pk(),
  key: stableKey(),
  kind: mediaKind('kind').notNull(),
  /** Public path or URL of the file (today: site-relative, e.g. "/images/x.jpg"). */
  src: text('src').notNull(),
  width: integer('width'),
  height: integer('height'),
  version: integer('version').notNull().default(1),
  ...audit(),
});

export const mediaTranslations = pgTable(
  'media_translations',
  {
    mediaId: uuid('media_id')
      .notNull()
      .references(() => media.id, { onDelete: 'cascade' }),
    locale: text('locale')
      .notNull()
      .references(() => locales.code),
    alt: text('alt').notNull(),
    ...audit(),
  },
  (t) => [primaryKey({ columns: [t.mediaId, t.locale] })]
);

const mediaRef = (name: string) => uuid(name).references(() => media.id, { onDelete: 'restrict' });

// ---------------------------------------------------------------------------
// Technologies
// ---------------------------------------------------------------------------

export const technologies = pgTable('technologies', {
  ...entity(),
  categoryNumber: text('category_number').notNull(),
  imageId: mediaRef('image_id').notNull(),
  ogImageId: mediaRef('og_image_id'),
  noindex: boolean('noindex').notNull().default(false),
});

export const technologyTranslations = pgTable(
  'technology_translations',
  {
    technologyId: uuid('technology_id')
      .notNull()
      .references(() => technologies.id, { onDelete: 'cascade' }),
    ...translation(),
    slug: text('slug').notNull(),
    categoryTitle: text('category_title').notNull(),
    title: text('title').notNull(),
    subtitle: text('subtitle').notNull(),
    overview: text('overview').notNull(),
    /** PatentInfoV1 | null */
    patentInfo: jsonb('patent_info'),
    /** TextListV1 */
    rawMaterials: jsonb('raw_materials').notNull(),
    /** TitleDescriptionListV1 */
    processPrinciples: jsonb('process_principles').notNull(),
    keyAdvantages: jsonb('key_advantages').notNull(),
    applications: jsonb('applications').notNull(),
    productsProduced: jsonb('products_produced').notNull(),
    ...seoTexts(),
  },
  (t) => [primaryKey({ columns: [t.technologyId, t.locale] }), unique('technology_translations_locale_slug').on(t.locale, t.slug)]
);

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------

export const projects = pgTable('projects', {
  ...entity(),
  categoryNumber: text('category_number').notNull(),
  imageId: mediaRef('image_id').notNull(),
  /** CSS object-position for the hero/card photo, if it needs a custom crop. */
  imagePosition: text('image_position'),
  relatedTechnologyId: uuid('related_technology_id')
    .notNull()
    .references(() => technologies.id, { onDelete: 'restrict' }),
  ogImageId: mediaRef('og_image_id'),
  noindex: boolean('noindex').notNull().default(false),
});

export const projectTranslations = pgTable(
  'project_translations',
  {
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    ...translation(),
    slug: text('slug').notNull(),
    category: text('category').notNull(),
    title: text('title').notNull(),
    country: text('country').notNull(),
    years: text('years').notNull(),
    capacity: text('capacity'),
    type: text('type').notNull(),
    overview: text('overview').notNull(),
    /** TextListV1 */
    scope: jsonb('scope').notNull(),
    technology: text('technology').notNull(),
    /** TextListV1 | null */
    results: jsonb('results'),
    /** LabelValueListV1 */
    specs: jsonb('specs').notNull(),
    ...seoTexts(),
  },
  (t) => [primaryKey({ columns: [t.projectId, t.locale] }), unique('project_translations_locale_slug').on(t.locale, t.slug)]
);

export const projectGallery = pgTable(
  'project_gallery',
  {
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'cascade' }),
    position: integer('position').notNull(),
    mediaId: mediaRef('media_id').notNull(),
  },
  (t) => [primaryKey({ columns: [t.projectId, t.position] })]
);

/** Technology → related projects, ordered. */
export const technologyProjects = pgTable(
  'technology_projects',
  {
    technologyId: uuid('technology_id')
      .notNull()
      .references(() => technologies.id, { onDelete: 'cascade' }),
    position: integer('position').notNull(),
    projectId: uuid('project_id')
      .notNull()
      .references(() => projects.id, { onDelete: 'restrict' }),
  },
  (t) => [primaryKey({ columns: [t.technologyId, t.position] }), unique('technology_projects_pair').on(t.technologyId, t.projectId)]
);

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

export const products = pgTable('products', {
  ...entity(),
  categoryNumber: text('category_number').notNull(),
  imageId: mediaRef('image_id').notNull(),
  relatedTechnologyId: uuid('related_technology_id')
    .notNull()
    .references(() => technologies.id, { onDelete: 'restrict' }),
  relatedProjectId: uuid('related_project_id')
    .notNull()
    .references(() => projects.id, { onDelete: 'restrict' }),
  ogImageId: mediaRef('og_image_id'),
  noindex: boolean('noindex').notNull().default(false),
});

export const productTranslations = pgTable(
  'product_translations',
  {
    productId: uuid('product_id')
      .notNull()
      .references(() => products.id, { onDelete: 'cascade' }),
    ...translation(),
    slug: text('slug').notNull(),
    categoryTitle: text('category_title').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    rawMaterials: jsonb('raw_materials').notNull(),
    productionTechnology: text('production_technology').notNull(),
    applications: jsonb('applications').notNull(),
    characteristics: jsonb('characteristics').notNull(),
    ...seoTexts(),
  },
  (t) => [primaryKey({ columns: [t.productId, t.locale] }), unique('product_translations_locale_slug').on(t.locale, t.slug)]
);

// ---------------------------------------------------------------------------
// EPC / EPCM stages, patents, videos
// ---------------------------------------------------------------------------

export const epcmStages = pgTable('epcm_stages', {
  ...entity(),
  /** Display number "01"…"08". */
  number: text('number').notNull(),
  imageId: mediaRef('image_id'),
});

export const epcmStageTranslations = pgTable(
  'epcm_stage_translations',
  {
    stageId: uuid('stage_id')
      .notNull()
      .references(() => epcmStages.id, { onDelete: 'cascade' }),
    ...translation(),
    title: text('title').notNull(),
    focus: text('focus').notNull(),
    description: text('description').notNull(),
    deliverables: jsonb('deliverables').notNull(),
  },
  (t) => [primaryKey({ columns: [t.stageId, t.locale] })]
);

export const patents = pgTable(
  'patents',
  {
    ...entity(),
    /** Where the record appears: "home" (IP cards) and/or "registry" (/technologies/patents). */
    placements: text('placements').array().notNull(),
    /** Patent / application number as printed (structural, not translated). */
    patentNo: text('patent_no').notNull(),
    legalStatus: patentLegalStatus('legal_status'),
    registryNumber: text('registry_number'),
    imageId: mediaRef('image_id'),
  },
  (t) => [check('patents_placements_valid', sql`${t.placements} <@ ARRAY['home','registry']::text[] AND cardinality(${t.placements}) > 0`)]
);

export const patentTranslations = pgTable(
  'patent_translations',
  {
    patentId: uuid('patent_id')
      .notNull()
      .references(() => patents.id, { onDelete: 'cascade' }),
    ...translation(),
    title: text('title').notNull(),
    statusLabel: text('status_label'),
    patentLabel: text('patent_label'),
    jurisdiction: text('jurisdiction'),
    abstract: text('abstract'),
    /** TextListV1 | null */
    claimsSummary: jsonb('claims_summary'),
    code: text('code'),
    location: text('location'),
    overview: text('overview'),
    /** TitleDescriptionListV1 | null */
    keyPillars: jsonb('key_pillars'),
    industrialImplementation: text('industrial_implementation'),
    imageCaption: text('image_caption'),
  },
  (t) => [primaryKey({ columns: [t.patentId, t.locale] })]
);

export const videos = pgTable('videos', {
  ...entity(),
  number: text('number').notNull(),
  videoId: mediaRef('video_id').notNull(),
  posterId: mediaRef('poster_id').notNull(),
});

export const videoTranslations = pgTable(
  'video_translations',
  {
    videoId: uuid('video_id')
      .notNull()
      .references(() => videos.id, { onDelete: 'cascade' }),
    ...translation(),
    category: text('category').notNull(),
    title: text('title').notNull(),
    headline: text('headline').notNull(),
    description: text('description').notNull(),
  },
  (t) => [primaryKey({ columns: [t.videoId, t.locale] })]
);

// ---------------------------------------------------------------------------
// Pages (fixed records with code-defined slots; no page builder)
// ---------------------------------------------------------------------------

export const pages = pgTable('pages', {
  ...entity(),
  /** Route or template key ("home", "company", "projectDetail", …). Set of pages is code-owned. */
  pageKey: text('page_key').notNull().unique(),
  kind: pageKind('kind').notNull(),
  hasHeader: boolean('has_header').notNull(),
  headerBadgeNumber: text('header_badge_number'),
  /** Order of the page's list keys (lists may be empty). */
  listKeys: text('list_keys').array().notNull(),
  hasSeo: boolean('has_seo').notNull(),
  ogImageId: mediaRef('og_image_id'),
  noindex: boolean('noindex').notNull().default(false),
});

export const pageTranslations = pgTable(
  'page_translations',
  {
    pageId: uuid('page_id')
      .notNull()
      .references(() => pages.id, { onDelete: 'cascade' }),
    ...translation(),
    headerBadgeLabel: text('header_badge_label'),
    headerTitle: text('header_title'),
    headerSubtitle: text('header_subtitle'),
    headerDescription: text('header_description'),
    /** LabelValueListV1 | null */
    headerMeta: jsonb('header_meta'),
    headerActionLabel: text('header_action_label'),
    /** PageCopyV1: ordered [{ slot, text }] */
    copy: jsonb('copy').notNull(),
    /** PageBodyV1 | null */
    body: jsonb('body'),
    ...seoTexts(),
  },
  (t) => [primaryKey({ columns: [t.pageId, t.locale] })]
);

export const pageMedia = pgTable(
  'page_media',
  {
    pageId: uuid('page_id')
      .notNull()
      .references(() => pages.id, { onDelete: 'cascade' }),
    slot: text('slot').notNull(),
    position: integer('position').notNull(),
    mediaId: mediaRef('media_id').notNull(),
  },
  (t) => [primaryKey({ columns: [t.pageId, t.slot] }), unique('page_media_position').on(t.pageId, t.position)]
);

export const pageListItems = pgTable(
  'page_list_items',
  {
    id: pk(),
    pageId: uuid('page_id')
      .notNull()
      .references(() => pages.id, { onDelete: 'cascade' }),
    listKey: text('list_key').notNull(),
    position: integer('position').notNull(),
    /** ListItemStructureV1 (json: key order preserved) */
    structure: json('structure').notNull(),
    schemaVersion: smallint('schema_version').notNull().default(1),
    ...audit(),
  },
  (t) => [unique('page_list_items_position').on(t.pageId, t.listKey, t.position)]
);

export const pageListItemTranslations = pgTable(
  'page_list_item_translations',
  {
    itemId: uuid('item_id')
      .notNull()
      .references(() => pageListItems.id, { onDelete: 'cascade' }),
    locale: text('locale')
      .notNull()
      .references(() => locales.code),
    /** ListItemTextsV1: slot path → text */
    texts: jsonb('texts').notNull(),
    schemaVersion: smallint('schema_version').notNull().default(1),
    ...audit(),
  },
  (t) => [primaryKey({ columns: [t.itemId, t.locale] })]
);

// ---------------------------------------------------------------------------
// Site settings (singleton), metrics, offices
// ---------------------------------------------------------------------------

export const settings = pgTable(
  'settings',
  {
    id: pk(),
    key: stableKey(),
    siteName: text('site_name').notNull(),
    primaryEmail: text('primary_email').notNull(),
    logoId: mediaRef('logo_id').notNull(),
    logoReversedId: mediaRef('logo_reversed_id').notNull(),
    footerBackgroundId: mediaRef('footer_background_id').notNull(),
    hqEmail: text('hq_email').notNull(),
    version: integer('version').notNull().default(1),
    ...audit(),
  },
  (t) => [check('settings_singleton', sql`${t.key} = 'settings'`)]
);

export const settingsTranslations = pgTable(
  'settings_translations',
  {
    settingsId: uuid('settings_id')
      .notNull()
      .references(() => settings.id, { onDelete: 'cascade' }),
    ...translation(),
    footerTagline: text('footer_tagline').notNull(),
    footerLocation: text('footer_location').notNull(),
    copyright: text('copyright').notNull(),
    footerBackgroundAlt: text('footer_background_alt').notNull(),
    hqName: text('hq_name').notNull(),
    hqAddressLine1: text('hq_address_line1').notNull(),
    hqAddressLine2: text('hq_address_line2').notNull(),
    hqShortAddress: text('hq_short_address').notNull(),
    hqJurisdiction: text('hq_jurisdiction').notNull(),
    hqHours: text('hq_hours').notNull(),
    defaultSiteTitle: text('default_site_title').notNull(),
    defaultSiteDescription: text('default_site_description').notNull(),
  },
  (t) => [primaryKey({ columns: [t.settingsId, t.locale] })]
);

export const metrics = pgTable('metrics', {
  id: pk(),
  key: stableKey(),
  position: integer('position').notNull().unique(),
  /** Value as printed, e.g. "25+"; null for text-only metrics. */
  value: text('value'),
  version: integer('version').notNull().default(1),
  ...audit(),
});

export const metricTranslations = pgTable(
  'metric_translations',
  {
    metricId: uuid('metric_id')
      .notNull()
      .references(() => metrics.id, { onDelete: 'cascade' }),
    locale: text('locale')
      .notNull()
      .references(() => locales.code),
    label: text('label').notNull(),
    highlight: text('highlight'),
    ...audit(),
  },
  (t) => [primaryKey({ columns: [t.metricId, t.locale] })]
);

export const offices = pgTable('offices', {
  id: pk(),
  key: stableKey(),
  position: integer('position').notNull(),
  phone: text('phone'),
  email: text('email').notNull(),
  whatsapp: text('whatsapp'),
  version: integer('version').notNull().default(1),
  ...audit(),
});

export const officeTranslations = pgTable(
  'office_translations',
  {
    officeId: uuid('office_id')
      .notNull()
      .references(() => offices.id, { onDelete: 'cascade' }),
    locale: text('locale')
      .notNull()
      .references(() => locales.code),
    region: text('region').notNull(),
    title: text('title').notNull(),
    country: text('country').notNull(),
    address: text('address'),
    representative: text('representative'),
    ...audit(),
  },
  (t) => [primaryKey({ columns: [t.officeId, t.locale] })]
);

// ---------------------------------------------------------------------------
// Redirects (internal targets only in v1 — approved architecture §11.3)
// ---------------------------------------------------------------------------

export const redirects = pgTable(
  'redirects',
  {
    id: pk(),
    key: stableKey(),
    fromPath: text('from_path').notNull().unique(),
    toPath: text('to_path').notNull(),
    statusCode: smallint('status_code').notNull().default(301),
    allLocales: boolean('all_locales').notNull().default(true),
    source: redirectSource('source').notNull().default('manual'),
    hits: integer('hits').notNull().default(0),
    lastHitAt: timestamp('last_hit_at', { withTimezone: true }),
    ...audit(),
  },
  (t) => [
    check('redirects_status_code', sql`${t.statusCode} IN (301, 302)`),
    // Absolute paths only: no scheme, no host, no protocol-relative "//", no backslash, no control characters.
    check('redirects_from_internal', sql`${t.fromPath} ~ '^/([^/\\\\[:cntrl:]][^\\\\[:cntrl:]]*)?$'`),
    check('redirects_to_internal', sql`${t.toPath} ~ '^/([^/\\\\[:cntrl:]][^\\\\[:cntrl:]]*)?$'`),
    check('redirects_not_self', sql`${t.fromPath} <> ${t.toPath}`),
  ]
);

// ===========================================================================
// Phase C: users, sessions, authentication factors, audit log
// (approved architecture §7, §8, §17.2; docs/admin-auth.md)
// ===========================================================================

export const userRole = pgEnum('user_role', ['owner', 'admin', 'content_manager', 'editor', 'seo_specialist', 'marketer']);
export const userStatus = pgEnum('user_status', ['active', 'disabled']);
export const auditResult = pgEnum('audit_result', ['success', 'failure', 'denied']);
export const webauthnChallengePurpose = pgEnum('webauthn_challenge_purpose', ['registration', 'authentication']);

const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
  dataType: () => 'bytea',
  toDriver: (v) => Buffer.from(v),
  fromDriver: (v) => new Uint8Array(v),
});

export const users = pgTable(
  'users',
  {
    id: pk(),
    /** Normalised (trimmed, lower-cased) e-mail; unique. */
    email: text('email').notNull(),
    name: text('name').notNull(),
    role: userRole('role').notNull(),
    status: userStatus('status').notNull().default('active'),
    /** Argon2id PHC string. Never logged, never returned by the API. */
    passwordHash: text('password_hash').notNull(),
    passwordChangedAt: timestamp('password_changed_at', { withTimezone: true }).notNull().defaultNow(),
    failedLogins: integer('failed_logins').notNull().default(0),
    lastFailedLoginAt: timestamp('last_failed_login_at', { withTimezone: true }),
    lockedUntil: timestamp('locked_until', { withTimezone: true }),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    version: integer('version').notNull().default(1),
    ...audit(),
  },
  (t) => [unique('users_email').on(t.email), check('users_email_normalised', sql`${t.email} = lower(btrim(${t.email}))`)]
);

export const sessions = pgTable(
  'sessions',
  {
    /** Public identifier (listing / revoking a session); never the secret. */
    id: pk(),
    /** SHA-256 of the 256-bit random session token (the cookie value). */
    tokenHash: text('token_hash').notNull().unique(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Authentication assurance: 1 = password only, 2 = password + second factor. */
    aal: smallint('aal').notNull().default(1),
    /** Last successful second-factor verification (step-up window). */
    mfaVerifiedAt: timestamp('mfa_verified_at', { withTimezone: true }),
    /** Failed second-factor attempts in this session (the session is revoked after 5). */
    mfaFailures: integer('mfa_failures').notNull().default(0),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    /** Absolute expiry; the idle timeout is enforced against last_seen_at. */
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ipHash: text('ip_hash'),
    userAgent: text('user_agent'),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    revokedReason: text('revoked_reason'),
  },
  (t) => [index('sessions_user').on(t.userId), check('sessions_aal', sql`${t.aal} IN (1, 2)`)]
);

/** Browsers that completed a full login before; per-account lockout does not apply to them (§19). */
export const knownDevices = pgTable(
  'known_devices',
  {
    tokenHash: text('token_hash').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  },
  (t) => [index('known_devices_user').on(t.userId)]
);

/** Passkeys / security keys. Only public data: the private key never leaves the authenticator. */
export const webauthnCredentials = pgTable(
  'webauthn_credentials',
  {
    id: pk(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Credential ID (base64url), globally unique. */
    credentialId: text('credential_id').notNull().unique(),
    /** COSE public key. */
    publicKey: bytea('public_key').notNull(),
    signCount: bigint('sign_count', { mode: 'number' }).notNull().default(0),
    transports: text('transports').array().notNull().default(sql`ARRAY[]::text[]`),
    deviceType: text('device_type').notNull(),
    backedUp: boolean('backed_up').notNull(),
    name: text('name').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  },
  (t) => [index('webauthn_credentials_user').on(t.userId)]
);

/** One-time WebAuthn challenges: short-lived, bound to a session and a purpose, consumed on use. */
export const webauthnChallenges = pgTable(
  'webauthn_challenges',
  {
    id: pk(),
    challenge: text('challenge').notNull().unique(),
    purpose: webauthnChallengePurpose('purpose').notNull(),
    sessionId: uuid('session_id')
      .notNull()
      .references(() => sessions.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    usedAt: timestamp('used_at', { withTimezone: true }),
  },
  (t) => [index('webauthn_challenges_session').on(t.sessionId)]
);

/** TOTP (RFC 6238) fallback factor. The secret is encrypted (AES-256-GCM, key id in the value). */
export const totpCredentials = pgTable('totp_credentials', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  secretEncrypted: text('secret_encrypted').notNull(),
  /** null while enrollment is pending confirmation. */
  confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
  /** Last accepted time step: a code can never be accepted twice. */
  lastTimeStep: bigint('last_time_step', { mode: 'number' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/** One-time recovery codes, stored as SHA-256 only (128-bit random codes). */
export const recoveryCodes = pgTable(
  'recovery_codes',
  {
    id: pk(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    codeHash: text('code_hash').notNull().unique(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    usedAt: timestamp('used_at', { withTimezone: true }),
  },
  (t) => [index('recovery_codes_user').on(t.userId)]
);

/** Password reset tokens: single use, 30 minutes, stored as SHA-256 only. */
export const passwordResets = pgTable(
  'password_resets',
  {
    tokenHash: text('token_hash').primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    usedAt: timestamp('used_at', { withTimezone: true }),
  },
  (t) => [index('password_resets_user').on(t.userId)]
);

/**
 * Append-only audit log (§17.2). The application role has INSERT and SELECT only, and a
 * trigger refuses UPDATE, DELETE and TRUNCATE even for the table owner
 * (drizzle/0003_audit_append_only.sql). Never contains passwords, tokens, codes or secrets.
 */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(),
    at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
    actorId: uuid('actor_id').references(() => users.id, { onDelete: 'restrict' }),
    action: text('action').notNull(),
    resourceType: text('resource_type'),
    resourceId: text('resource_id'),
    result: auditResult('result').notNull(),
    requestId: text('request_id'),
    ipHash: text('ip_hash'),
    userAgent: text('user_agent'),
    /** AuditSummaryV1: action-specific details without personal data or secrets. */
    summary: jsonb('summary').notNull().default(sql`'{}'::jsonb`),
    schemaVersion: smallint('schema_version').notNull().default(1),
  },
  (t) => [index('audit_events_at').on(t.at), index('audit_events_actor').on(t.actorId), index('audit_events_request').on(t.requestId)]
);

