/**
 * Per-language bundles: UI strings (src/i18n/ui/<locale>.json) + resolved content snapshot
 * (src/content/snapshot/<locale>.json, generated by scripts/content/build-snapshots.ts).
 *
 * English is bundled with the app; every other language is code-split and downloaded only
 * when used — the same loading behaviour the site had with its old dictionaries.
 */
import { DEFAULT_LOCALE, Locale } from './config';
import enUi from './ui/en.json';
import enContent from '../content/snapshot/en.json';
import { ContentApi, createContentApi } from '../content/getters';
import type { ContentSnapshot } from '../content/types';

/** Every UI string key. Generated from the English file: unknown keys fail type checking. */
export type UiKey = keyof typeof enUi;
export type UiDictionary = Record<UiKey, string>;

export interface LocaleBundle {
  ui: UiDictionary;
  content: ContentApi;
}

type RawBundle = { ui: UiDictionary; content: ContentSnapshot };

const loaders: Record<Exclude<Locale, 'en'>, () => Promise<RawBundle>> = {
  ru: async () => ({ ui: (await import('./ui/ru.json')).default, content: (await import('../content/snapshot/ru.json')).default as unknown as ContentSnapshot }),
  zh: async () => ({ ui: (await import('./ui/zh.json')).default, content: (await import('../content/snapshot/zh.json')).default as unknown as ContentSnapshot }),
  tr: async () => ({ ui: (await import('./ui/tr.json')).default, content: (await import('../content/snapshot/tr.json')).default as unknown as ContentSnapshot }),
  ar: async () => ({ ui: (await import('./ui/ar.json')).default, content: (await import('../content/snapshot/ar.json')).default as unknown as ContentSnapshot }),
  es: async () => ({ ui: (await import('./ui/es.json')).default, content: (await import('../content/snapshot/es.json')).default as unknown as ContentSnapshot }),
};

const toBundle = (raw: RawBundle): LocaleBundle => ({ ui: raw.ui, content: createContentApi(raw.content) });

const cache: Partial<Record<Locale, LocaleBundle>> = {
  [DEFAULT_LOCALE]: toBundle({ ui: enUi, content: enContent as unknown as ContentSnapshot }),
};

export function getBundle(locale: Locale): LocaleBundle | undefined {
  return cache[locale];
}

export async function loadBundle(locale: Locale): Promise<LocaleBundle> {
  const cached = cache[locale];
  if (cached) return cached;
  const bundle = toBundle(await loaders[locale as Exclude<Locale, 'en'>]());
  cache[locale] = bundle;
  return bundle;
}

/** Server-side rendering: register a language synchronously. */
export function primeBundle(locale: Locale, raw: RawBundle): void {
  cache[locale] = toBundle(raw);
}

export const englishUi: UiDictionary = enUi;
